../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/ew.txt > ../tumblr_twitter_scrapper/tweets/arpa/ew.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/entertainmentweekly.txt > ../tumblr_twitter_scrapper/posts/arpa/entertainmentweekly.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/truthdogg.txt > ../tumblr_twitter_scrapper/tweets/arpa/truthdogg.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/truthdogg.txt > ../tumblr_twitter_scrapper/posts/arpa/truthdogg.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/RafiDAngelo.txt > ../tumblr_twitter_scrapper/tweets/arpa/RafiDAngelo.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/rafi-dangelo.txt > ../tumblr_twitter_scrapper/posts/arpa/rafi-dangelo.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/NARAL.txt > ../tumblr_twitter_scrapper/tweets/arpa/NARAL.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/prochoiceamerica.txt > ../tumblr_twitter_scrapper/posts/arpa/prochoiceamerica.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/bonniekristian.txt > ../tumblr_twitter_scrapper/tweets/arpa/bonniekristian.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/bonniekristian.txt > ../tumblr_twitter_scrapper/posts/arpa/bonniekristian.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/fullmarxshef.txt > ../tumblr_twitter_scrapper/tweets/arpa/fullmarxshef.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/fullmarx.txt > ../tumblr_twitter_scrapper/posts/arpa/fullmarx.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/KeatonPatti.txt > ../tumblr_twitter_scrapper/tweets/arpa/KeatonPatti.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/keatonpatti.txt > ../tumblr_twitter_scrapper/posts/arpa/keatonpatti.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/nukirk.txt > ../tumblr_twitter_scrapper/tweets/arpa/nukirk.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/thoughtremixer.txt > ../tumblr_twitter_scrapper/posts/arpa/thoughtremixer.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/la_liberty.txt > ../tumblr_twitter_scrapper/tweets/arpa/la_liberty.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/laliberty.txt > ../tumblr_twitter_scrapper/posts/arpa/laliberty.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/WarsofASOIAF.txt > ../tumblr_twitter_scrapper/tweets/arpa/WarsofASOIAF.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/warsofasoiaf.txt > ../tumblr_twitter_scrapper/posts/arpa/warsofasoiaf.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/idragonsdaily.txt > ../tumblr_twitter_scrapper/tweets/arpa/idragonsdaily.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/imaginedragonsdaily.txt > ../tumblr_twitter_scrapper/posts/arpa/imaginedragonsdaily.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/psliterary.txt > ../tumblr_twitter_scrapper/tweets/arpa/psliterary.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/psliterary.txt > ../tumblr_twitter_scrapper/posts/arpa/psliterary.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/explorer.txt > ../tumblr_twitter_scrapper/tweets/arpa/explorer.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/explore-blog.txt > ../tumblr_twitter_scrapper/posts/arpa/explore-blog.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/@glenfitzjerrell.txt > ../tumblr_twitter_scrapper/tweets/arpa/@glenfitzjerrell.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/unkaglen.txt > ../tumblr_twitter_scrapper/posts/arpa/unkaglen.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/LeoHCharmed.txt > ../tumblr_twitter_scrapper/tweets/arpa/LeoHCharmed.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/leohearts.txt > ../tumblr_twitter_scrapper/posts/arpa/leohearts.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/kingsmanmovie.txt > ../tumblr_twitter_scrapper/tweets/arpa/kingsmanmovie.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/kingsman-network.txt > ../tumblr_twitter_scrapper/posts/arpa/kingsman-network.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/Gotham.txt > ../tumblr_twitter_scrapper/tweets/arpa/Gotham.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/justgotham.txt > ../tumblr_twitter_scrapper/posts/arpa/justgotham.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/intrainingdoc.txt > ../tumblr_twitter_scrapper/tweets/arpa/intrainingdoc.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/intrainingdoc.txt > ../tumblr_twitter_scrapper/posts/arpa/intrainingdoc.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/dccomics.txt > ../tumblr_twitter_scrapper/tweets/arpa/dccomics.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/dcfilms.txt > ../tumblr_twitter_scrapper/posts/arpa/dcfilms.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/@autselfadvocacy.txt > ../tumblr_twitter_scrapper/tweets/arpa/@autselfadvocacy.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/autisticadvocacy.txt > ../tumblr_twitter_scrapper/posts/arpa/autisticadvocacy.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/asexualstudies.txt > ../tumblr_twitter_scrapper/tweets/arpa/asexualstudies.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/asexualresearch.txt > ../tumblr_twitter_scrapper/posts/arpa/asexualresearch.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/Pantmonger.txt > ../tumblr_twitter_scrapper/tweets/arpa/Pantmonger.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/pantmonger.txt > ../tumblr_twitter_scrapper/posts/arpa/pantmonger.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/dylanobrien.txt > ../tumblr_twitter_scrapper/tweets/arpa/dylanobrien.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/dylan-source.txt > ../tumblr_twitter_scrapper/posts/arpa/dylan-source.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/jbuffyangel.txt > ../tumblr_twitter_scrapper/tweets/arpa/jbuffyangel.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/jbuffyangel.txt > ../tumblr_twitter_scrapper/posts/arpa/jbuffyangel.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/CW_Riverdale.txt > ../tumblr_twitter_scrapper/tweets/arpa/CW_Riverdale.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/fyeahriverdale.txt > ../tumblr_twitter_scrapper/posts/arpa/fyeahriverdale.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/realjonghyun90.txt > ../tumblr_twitter_scrapper/tweets/arpa/realjonghyun90.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/fyjjong.txt > ../tumblr_twitter_scrapper/posts/arpa/fyjjong.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/bellarkefiction.txt > ../tumblr_twitter_scrapper/tweets/arpa/bellarkefiction.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/bellarkefanfiction.txt > ../tumblr_twitter_scrapper/posts/arpa/bellarkefanfiction.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/kaisooficrec_.txt > ../tumblr_twitter_scrapper/tweets/arpa/kaisooficrec_.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/kaisooficrec.txt > ../tumblr_twitter_scrapper/posts/arpa/kaisooficrec.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/marvel.txt > ../tumblr_twitter_scrapper/tweets/arpa/marvel.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/marvelgifs.txt > ../tumblr_twitter_scrapper/posts/arpa/marvelgifs.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/BTS_Trans.txt > ../tumblr_twitter_scrapper/tweets/arpa/BTS_Trans.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/bts-trans.txt > ../tumblr_twitter_scrapper/posts/arpa/bts-trans.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/leamichelenews1.txt > ../tumblr_twitter_scrapper/tweets/arpa/leamichelenews1.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/leamichele-news.txt > ../tumblr_twitter_scrapper/posts/arpa/leamichele-news.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/TylerKnott.txt > ../tumblr_twitter_scrapper/tweets/arpa/TylerKnott.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/tylerknott.txt > ../tumblr_twitter_scrapper/posts/arpa/tylerknott.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/UnbelievableFts.txt > ../tumblr_twitter_scrapper/tweets/arpa/UnbelievableFts.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/unbelievable-facts.txt > ../tumblr_twitter_scrapper/posts/arpa/unbelievable-facts.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/phanficofficial.txt > ../tumblr_twitter_scrapper/tweets/arpa/phanficofficial.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/phanfic.txt > ../tumblr_twitter_scrapper/posts/arpa/phanfic.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/darrenchrisnews.txt > ../tumblr_twitter_scrapper/tweets/arpa/darrenchrisnews.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/darrenandchrisnews.txt > ../tumblr_twitter_scrapper/posts/arpa/darrenandchrisnews.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/missing_light.txt > ../tumblr_twitter_scrapper/tweets/arpa/missing_light.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/missing-light.txt > ../tumblr_twitter_scrapper/posts/arpa/missing-light.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/thinksquad.txt > ../tumblr_twitter_scrapper/tweets/arpa/thinksquad.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/thinksquad.txt > ../tumblr_twitter_scrapper/posts/arpa/thinksquad.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/LDRChronicles.txt > ../tumblr_twitter_scrapper/tweets/arpa/LDRChronicles.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/lanadelreychronicles.txt > ../tumblr_twitter_scrapper/posts/arpa/lanadelreychronicles.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/pointlesslettrs.txt > ../tumblr_twitter_scrapper/tweets/arpa/pointlesslettrs.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/pointless-letters.txt > ../tumblr_twitter_scrapper/posts/arpa/pointless-letters.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/@ALALibrary.txt > ../tumblr_twitter_scrapper/tweets/arpa/@ALALibrary.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/libraryadvocates.txt > ../tumblr_twitter_scrapper/posts/arpa/libraryadvocates.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/netlex.txt > ../tumblr_twitter_scrapper/tweets/arpa/netlex.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/netlex.txt > ../tumblr_twitter_scrapper/posts/arpa/netlex.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/chartier.txt > ../tumblr_twitter_scrapper/tweets/arpa/chartier.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/chartier.txt > ../tumblr_twitter_scrapper/posts/arpa/chartier.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/shaerahaek.txt > ../tumblr_twitter_scrapper/tweets/arpa/shaerahaek.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/shaerahaek.txt > ../tumblr_twitter_scrapper/posts/arpa/shaerahaek.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/jjong93_net.txt > ../tumblr_twitter_scrapper/tweets/arpa/jjong93_net.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/ifntjjong.txt > ../tumblr_twitter_scrapper/posts/arpa/ifntjjong.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/alohaspaceman.txt > ../tumblr_twitter_scrapper/tweets/arpa/alohaspaceman.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/alohaspaceman.txt > ../tumblr_twitter_scrapper/posts/arpa/alohaspaceman.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/buzzfeed.txt > ../tumblr_twitter_scrapper/tweets/arpa/buzzfeed.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/buzzfeed.txt > ../tumblr_twitter_scrapper/posts/arpa/buzzfeed.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/callistawolf.txt > ../tumblr_twitter_scrapper/tweets/arpa/callistawolf.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/callistawolf.txt > ../tumblr_twitter_scrapper/posts/arpa/callistawolf.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/vintagefangirla.txt > ../tumblr_twitter_scrapper/tweets/arpa/vintagefangirla.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/vintagefangirlannie.txt > ../tumblr_twitter_scrapper/posts/arpa/vintagefangirlannie.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/amccalltoarms.txt > ../tumblr_twitter_scrapper/tweets/arpa/amccalltoarms.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/amccalltoarms.txt > ../tumblr_twitter_scrapper/posts/arpa/amccalltoarms.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/viivacious.txt > ../tumblr_twitter_scrapper/tweets/arpa/viivacious.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/vivacious.txt > ../tumblr_twitter_scrapper/posts/arpa/vivacious.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/tweets/text/flynneware.txt > ../tumblr_twitter_scrapper/tweets/arpa/flynneware.arpa
../kenlm/bin/lmplz -o 3 <../tumblr_twitter_scrapper/posts/text/flynneware.txt > ../tumblr_twitter_scrapper/posts/arpa/flynneware.arpa
